using System;
using System.Runtime.Serialization;

namespace GolfNow.Mobile.Models.DataContracts
{
    /// <summary>
    /// An invoice bundled with an override reference ID, generated by calling RequestOverrideTeeTimeInvoice.
    /// </summary>
    [DataContract]
    public class RateOverrideTeeTimeInvoice
    {
        /// <summary>
        /// The overriden invoice.
        /// </summary>
        [DataMember]
        public TeeTimeInvoice Invoice
        {
            get;
            set;
        }

        /// <summary>
        /// The reference ID generated by the request.
        /// </summary>
        [DataMember]
        public string OverrideReferenceId
        {
            get;
            set;
        }
    }
}
